const hamburger = document.querySelector('.ham')
// console.log(hamburger)
const navsub = document.querySelector('.nav-sub')
const navBar = document.getElementById('top-bar')
hamburger.addEventListener('click', (e) => {
  hamburger.classList.toggle('change')
  // console.log(e.target)
  navsub.classList.toggle('nav-display')
  navsub.classList.toggle('nav-change')
})
